"""
Django settings for resume project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# =============================
# BASE DIR
# =============================
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================
# SECURITY
# =============================
SECRET_KEY = 'django-insecure-p@ci^zgo$$8r^&iysx8w=$&ooelb2id!4($!qh#ye7kt*a6d^v'
DEBUG = True
ALLOWED_HOSTS = []


# =============================
# APPLICATIONS
# =============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local app
    'analyzer',
]


# =============================
# MIDDLEWARE
# =============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =============================
# URLS
# =============================
ROOT_URLCONF = 'resume.urls'


# =============================
# TEMPLATES
# =============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # 👇 Custom templates directory
        'DIRS': [BASE_DIR / 'analyzer' / 'templates'],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =============================
# WSGI
# =============================
WSGI_APPLICATION = 'resume.wsgi.application'


# =============================
# DATABASE
# =============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# =============================
# PASSWORD VALIDATION
# =============================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================
# INTERNATIONALIZATION (FIXED ✅)
# =============================

LANGUAGE_CODE = 'en-us'

# ✅ FIX: Indian Timezone
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

# ✅ Keep this TRUE (Django best practice)
USE_TZ = True


# =============================
# STATIC FILES
# =============================
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'analyzer' / 'static'
]


# =============================
# DEFAULT PRIMARY KEY
# =============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================
# AUTH REDIRECTS (CORRECT ✅)
# =============================
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'
